apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: patadeveludo
type: Opaque
stringData:
  jwt-secret: CHANGE_ME_IN_PRODUCTION
  mp-access-token: YOUR_MP_ACCESS_TOKEN
  mp-webhook-secret: YOUR_MP_WEBHOOK_SECRET
  db-password: CHANGE_ME_IN_PRODUCTION
