apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: patadeveludo
resources:
  - namespace.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - postgres/secret.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - backend/secret.yaml
  - backend/configmap.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml
  - backend/ingress.yaml
  - frontend/configmap.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml
  - frontend/ingress.yaml
  - admin-frontend/configmap.yaml
  - admin-frontend/deployment.yaml
  - admin-frontend/service.yaml
  - admin-frontend/hpa.yaml
  - admin-frontend/ingress.yaml
