apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-frontend-config
  namespace: patadeveludo
data:
  NEXT_PUBLIC_API_URL: "https://api.patadeveludo.com.br/api"
  NEXT_PUBLIC_ADMIN_API_URL: "https://api.patadeveludo.com.br/api/admin"
