apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-frontend
  namespace: patadeveludo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      labels:
        app: admin-frontend
    spec:
      containers:
        - name: admin-frontend
          image: ghcr.io/stpedr/patadeveludo-admin:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: admin-frontend-config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
