apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-frontend
  namespace: patadeveludo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - admin.patadeveludo.com.br
      secretName: admin-frontend-tls
  rules:
    - host: admin.patadeveludo.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-frontend
                port:
                  number: 3000
